"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AudioPlayer from 'react-h5-audio-player';
import React, { useState, useEffect } from "react";

import "./globals.css";
import "./globals2.css";
import "./globals3.css";
import "./globals4.css";

export const PageContext = React.createContext(null);

const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [currentSong, setSong] = useState("")

  return (
    <html lang="en">
      <PageContext.Provider value={setSong}><body className={inter.className}>{children}
      {currentSong.length == 0 ? <AudioPlayer  src={currentSong} className="audio-player-hidden"></AudioPlayer> : <AudioPlayer  src={currentSong} className="audio-player"></AudioPlayer>}
      </body></PageContext.Provider>
    </html>
  );
}

